doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/MailWatch/Migrations'
    # namespace is arbitrary but should be different from MailWatch\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
